getwd()
setwd("D:/R/Project/assg3")
getwd()
unzip("rprog_data_ProgAssignment3-data.zip")
outcome<-read.csv("outcome-of-care-measures.csv",colClasses = "character")
head(outcome)
ncol(outcome)
nrow(outcome)
names(outcome)
outcome[,11]<-as.numeric(outcome[,11])
hist(outcome[,11])
